### ISSUE TITLE
'delete's aren't being forwarded to the backup server when in failover route

### ISSUE THREAD

**Issue by jkchin** [facebook/mcrouter#105]
I'm using a 'FailoverRoute' to failover all commands from the 'default' pool to the 'single' pool in an event of a failure in the default pool.

In my case, server '192.168.4.135' went offline for an extended period of time (inaccessible by icmp pings). Hence all commands are routed to the remaining default server "192.168.4.136" and the backup servers "mt1-memche101:11211", "mt1-memche102:11211"

I notice that the SET's and GET's were working correctly, but the 'DELETE' was always returning "NOT_FOUND" even though the key I wanted to retrieve is accessible via the 'GET'. I also verified that I can 'GET' that key from the backup server, and was also able to manually 'DELETE' it from the backup server.

Is this the expected behavior, and if so what's the rationale? My (perhaps unrealistic) expectation is that once we're in failover mode, all commands will be failed over to the backup server, not just GET and SET's.

Example workflow of the issue:
1. GET command on mcrouter shows that the key exists
```$ echo "get LOGICAL-QUESTION-BY-ID-30569" | nc 127.0.0.1 11211
VALUE LOGICAL-QUESTION-BY-ID-30569 1 313
?cdogpile.cache.api
CachedValue
END```
2. But the DELETE command on mcrouter shows that it's no found
```$ echo "delete LOGICAL-QUESTION-BY-ID-30569" | nc 127.0.0.1 11211
NOT_FOUND```
3. However the key is located in a backup server.
```
$ echo "get LOGICAL-QUESTION-BY-ID-30569" | nc 192.168.4.135 11211
$ echo "get LOGICAL-QUESTION-BY-ID-30569" | nc mt1-memche101 11211
END
$ echo "get LOGICAL-QUESTION-BY-ID-30569" | nc mt1-memche102 11211
VALUE LOGICAL-QUESTION-BY-ID-30569 1 313
?cdogpile.cache.api
CachedValue
END
```
4. And deleting the key manually off the backup server works.
```
$ echo "delete LOGICAL-QUESTION-BY-ID-30569" | nc mt1-memche102 11211
DELETED
$ echo "get LOGICAL-QUESTION-BY-ID-30569" | nc mt1-memche102 11211
END
```
Config
```
{
    "pools": {
        "default": {
            "servers": ["192.168.4.135:11211", "192.168.4.136:11211"]
         },
        "single": {
            "servers": [ "192.168.4.135:11211" ]
        },
        "backup": {
            "servers": ["mt1-memche101:11211", "mt1-memche102:11211"]
        }
    },
    "named_handles": [
        // Broadcast all calls to all nodes in the pool. This allows clients with and without mcrouter to coexist
        {
            "name": "Broadcast",
            "type": "OperationSelectorRoute",
            "operation_policies": {
                "add": "AllFastestRoute|Pool|default",
                "delete": "AllFastestRoute|Pool|default",
                "set": "AllFastestRoute|Pool|default",
                "get": {
                    "type": "AllSyncRoute",
                    "children": ["Pool|default"]
                },
            }
        },
        // Uses default 'sharded' routing with failover capabilities
        {
            "name": "ShardedFailover",
            "type": "FailoverRoute",
            "children": ["PoolRoute|default", "PoolRoute|backup"]
        },
        // Uses 'Broadcast' routing with failover capabilities
        {
            "name": "BroadcastFailover",
            "type": "FailoverRoute",
            "children": ["Broadcast", "PoolRoute|backup"]
        },
        // Routes to a single server, with auto-failover
        {
            "name": "TransparentFailover",
            "type": "FailoverRoute",
            "children": ["PoolRoute|single", "PoolRoute|backup"]
        },
    ],
    "route": "TransparentFailover"
}
```

**Comment by jkchin** [comment]
I also noticed in the docs about DELETE's behavior to report NOT_FOUND and how using `--asynclog-disable` would fix the issue.

What's unexpected for me is that if I use PoolRoute and send a DELETE to a dead server, I'll get 'SERVER_ERROR', while sending DELETE to a dead server that's on FailoverRoute would show 'NOT_FOUND'

https://github.com/facebook/mcrouter/wiki/Error-Handling#ascii
```
If the underlying server (e.g. memcached) is talking to mcrouter using the ASCII protocol, these are the errors that will be forwarded:

For get: By default no errors are returned for gets, mcrouter will always return a miss. However, if the option --disable-miss-on-get-errors is provided, all errors (i.e. both SERVER_ERROR and CLIENT_ERROR) will be forwarded.
For set: All errors (i.e. both SERVER_ERROR and CLIENT_ERROR).
For delete: By default, only errors of type: CLIENT_ERROR are forwarded, meaning that all other errors result in NOT_FOUND. This behavior can be modified if the option --asynclog-disable is specified, in which case all errors (i.e. both SERVER_ERROR and CLIENT_ERROR) will be forwarded to the client.```

**Comment by jmswen** [comment]
Hi @jkchin, thank you for the detailed information in the issue.  It sounds like you were able to mostly resolve your issue by reading about the behavior of the `--asynclog-disable` option.  None of the behavior you encountered would be considered unexpected, but I can try to offer some extra explanation about the behavior you're seeing.

If you just have a `PoolRoute`, then all operations on a given key will always go to the same server (based on some hash of the key).  If you want to `delete keyabc` and the server corresponding to `keyabc` is down, then it makes sense for mcrouter to report back that a `SERVER_ERROR` was encountered.

It's less clear what should happen in a `FailoverRoute`.  Let's say you have two memcached servers, `A` and `B`.  If `A` is down (hopefully just transiently), you failover to `B`.  Say `A` is up and responsive 90%+ of the time; a small fraction of requests failover to `B`.  As you noted, gets and sets (by default) will failover to `B` when `A` is unresponsive, but what's the right way to handle deletes?  

If asynclog is enabled, deletes are logged to disk if mcrouter cannot send them successfully to `A` (and mcrouter just reports `NOT_FOUND` instead of `DELETED` so you can tell the delete was logged to disk).  When `A` becomes responsive again, we want to re-send those deletes to `A` so we don't have stale/inconsistent data in the cache.  Your asynclog consumer (not supplied in mcrouter) would be responsible for attempting to resend spooled deletes to `A` periodically until successful.

If asynclog is disabled, then mcrouter just does the best it can with a delete request: failover (by default, unless you override this behavior in `failover_errors` in your `FailoverRoute` configuration).  This may or may not be what you really want: what if `A` becomes responsive after a transient error and now is serving stale data?  I don't have a good answer to this; it would be up to the client to handle this scenario.

Let me know if you have any further questions about this issue before I close it.

**Comment by jkchin** [comment]
Thanks for the detailed explanation.

What would you recommend for dealing with the DELETES for non transient down time of primary servers?

Sounds like keeping `asynclog-disable` enabled is still very useful. Hence I'm thinking I should create a 'OperationSelectorRoute' where the current auto failover behavior still occurs for GETs and SETs, but create a 'delete' policy to best effort attempt to broadcast deletes to all pools. Would this be a recommended configuration, or are there better


```
    "named_handles": [
        {
            "name": "FO",
            "type": "FailoverRoute",
            "children": ["PoolRoute|default", "PoolRoute|backup"]
        },
        {
            "name": "FOv2",
            "type": "OperationSelectorRoute",
            "default_policy": "FO",
            "operation_policies": {
                "delete": {
                    "type": "AllFastestRoute",
                    "children": ["Pool|default", "Pool|backup"]
                },
            }
        }
    ],
    "route": "FOv2"
```

**Comment by jmswen** [comment]
@jkchin, something similar to what you propose sounds reasonable, if spooling deletes to disk is not an option for you.  You may consider using a `FailoverRoute` policy for all `get` requests, and an `AllSyncRoute` policy for all `set` and `delete` requests.

**Comment by jkchin** [comment]
Thanks for the help! I tried 'AllSyncRoute' and it returns 'SERVER_ERROR unavailable' for a DELETE when the primary server is dead but when the backup server is up. However it still did the job of deleting the keys. I'll stick with AllFastestRoute for non-error replies

**Comment by jmswen** [comment]
Sorry, I meant `AllFastestRoute` if reliability is going to be an issue. :)  `AllSyncRoute` wouldn't be what you want, since it will return the worst reply received from all servers.

**Comment by jkchin** [comment]
Awesome thanks!

I tested out `AllFastestRoute` and realize that DELETE's will yield either 'NOT_FOUND' or 'DELETE' when both primary and backup are up depending on whether the backup or the primary pool replied first.

I then tried out 'MissFailoverRoute' which give the most consistent result in cases where the primary is up, and down. When the primary is up, DELETE's will yield 'DELETED' if it's found in the primary pool, and only make the extra trip to the backup pool if it's 'NOT_FOUND'. This saves us 1 extra trip to the backup pool compared to the 'AllFastestRoute' or 'AllSyncRoute'. When the primary is down for extended time, the asynclog feature will yield a 'NOT_FOUND' for DELETE's in the primary pool, and now the 'MissFailoverRoute' will then send the 'DELETE' to the backup pool where it'll be correctly 'DELETED'
