### ISSUE TITLE
mcrouter Crc32 hashing causing misses?

### ISSUE THREAD

**Issue by aboutte** [facebook/mcrouter#109]
I am in the process of migrating an application from datacenter A to datacenter B and this migration will require that our cache layer be kept in sync between the two datacenters.  I have mcrouter up and running (mcrouter: d96dbea, folly: 91499a6) with the following configuration:
 
```
{
  "pools": {
    "A": {
      "servers":
["memcached01:11211", "memcached02:11211"]
    }
  },
  "route": [
    {
      "type": "HashRoute",
      "hash_func": "Crc32",
      "children": "Pool|A"
    }
  ]
}
```

My next step in this application migration is to place mcrouter between my application and cache layer.  To validate that mcrouter will map keys to the same memcache server I captured a large number of cache keys in memcached01 and performed a get through mcrouter.  I was expecting mcrouter to route all my requests to memcached01 but I received about a 50% hit rate.  

My application is PHP and I have the following settings in my php.ini:

memcache.hash_function => crc32
memcache.hash_strategy => consistent 

Is there something I am missing in my mcrouter configuration?  Or is there something special about mcrouters implementation of crc32 versus the PHP implementation?  

I would appreciate any insight you may be able to provide.

**Comment by andreazevedo** [comment]
Hello @aboutte,

Currently mcrouter doesn't support crc32 with a consistent distribution.
For consistent hashing in mcrouter you will need to use `ch3`, but I'm afraid it is not compatible with crc32 + ketama used by php_libmemcached (meaning that you would still see those misses).

For your datacenter migration - and if you can't afford to have those misses, we can solve the problem by temporarily having 2 mcrouters. Let me know if you need help to set it up!

**Comment by aboutte** [comment]
@andreazevedo Thanks so much for the quick reply and the details!  

> For your datacenter migration - and if you can't afford to have those misses - we can solve the problem by temporarily having 2 mcrouters. Let me know if you need help to set it up!

When you say 2 mcrouters is [this](https://docs.google.com/drawings/d/1AGyvt1hWdWug7Ergvka8bXDVb6SNNDx39DGsK4kaJag/edit?usp=sharing) the idea that you had?  Each mcrouter would be configured with one local and one remote memcache server and the hashing would only take place in the application memcache client?

If that is what you are thinking I would be very curious to hear how you would recommend configuring mcrouter for this scenario.   

Would something like this be sufficient? 

```
{
  "pools": {
    "local": {
      "servers": [
        "memcache01-local:11211"
      ]
    },
    "remote": {
      "servers": [
        "memcache01-remote:11211"
      ]
    }
  },
  "route": {
    "type": "OperationSelectorRoute",
    "operation_policies": {
      "get": {
        "type": "PoolRoute",
        "children": [
          "PoolRoute|local"
        ]
      }
    },
    "default_policy": {
      "type": "AllFastestRoute",
      "children": [
        "PoolRoute|local",
        "PoolRoute|remote"
      ]
    }
  }
}
```

**Comment by andreazevedo** [comment]
Yes, that's a good configuration.
It would look something like [this](https://docs.google.com/drawings/d/1U5s51uaycCNZfCMGS0lvGBNp76LsEnibN7k2CBkwmW4/edit?usp=sharing) (red lines represents cross-datacenter communication).
As you said, all the hashing would be done by PHP and you would replace in your php config memcache1 by mcrouter1 and memcached2 by mcrouter2. Then, mcrouter1 talks only to memcache1 of each datacenter. Similarly, mcrouter2 always talks only to memcached2.

The only thing I would change in your config to make sure your cache is consistent is replace the `AllFastestRoute` with `AllSyncRoute`. Sure, you would have larger latency for `set` and `delete`, but that is usually fine as long as the `get` latency is kept low.

Now, do you want to keep using mcrouter after the migration? If you don't, then that's the end of the story. :)
If you want to keep mcrouter, you can set it up to warmup another pool using the `ch3` hash function, so that you can start using just one mcrouter. Let me know you need help for that! :)

**Comment by aboutte** [comment]
Thank you so much for the feedback @andreazevedo!  We are going to be moving forward with putting mcrouter in place to start this migration.  

Do you think the following configuration would be a good first step to minimize change before switching over to the multi data center setup:

```
{
  "pools": {
    "local": {
      "servers": [
        "memcache01-local:11211"
      ]
    }
  },
  "route": [
    {
      "type": "PoolRoute",
      "children": "Pool|local"
    }
  ]
}
```

We are planning on using mcrouter after the migration.  After the migration I will need to scale our cache tier horizontally and look at having a warm cache in another AWS region.  

I have been working with mcrouter on and off for a few months now and really enjoy working with it.  I appreciate what you and your team have built!

 The only pain point I have right now is compiling mcrouter.  Our environment consists have amazon linux, centos, or rhel so it was a bit of a pain to get mcrouter compiled.  Do you have any plans to distribute mcrouter packages?  Or a spec file so I can build an rpm?

Thanks agains for your support!

**Comment by andreazevedo** [comment]
Yes, that's a great first step! And I'm glad to know that mcrouter is being useful for you!

We are aware that mcrouter can be painful to build, specially in non-ubuntu distributions. The good news is that distributing mcrouter packages is in our roadmap, we are working on it!

**Comment by aboutte** [comment]
@andreazevedo Thanks for all the support!  I was able to get mcrouter into production and our memcache pool is warming in AWS.

```
STAT memcached01-local:11211:TCP:ascii-1000 avg_latency_us:241.044 pending_reqs:1 inflight_reqs:2 up:12; deleted:53453 found:64360613 notfound:1195302 notstored:787256 stored:1383267
STAT memcached01-remote:11211:TCP:ascii-1000 avg_latency_us:32305.782 pending_reqs:0 inflight_reqs:2 up:12; deleted:2316 notfound:4177 notstored:82023 stored:71490
```

I do have a few more questions for you:

- Can you you either point me in the direction of some documentation or explain the `notstored` field? What causes that field to get incremented?

- Do you have any recommendations for tuning the mcrouter host?  For example: IRQ affinity, NIC interrupt coalescing, NIC ring buffer size, etc.  Any insight on how you do it at FaceBook would be awesome!

Thanks again!

**Comment by andreazevedo** [comment]
Hello @aboutte,

What command are you using for your updates? `add`? `not_stored` simply means that the data was not stored :). If you are using `add` instead of `set` for example, it means that data was already present in memcached.

About tuning, it really depends on your hardware. We had different settings for different network cards here. So it really hard to help you with that, sorry. :(

Thank you

**Comment by andreazevedo** [comment]
@aboutte please, let us know if you need anything else! :)
