### ISSUE TITLE
WarmUpRoute - sets only to cold

### ISSUE THREAD

**Issue by Shaps** [facebook/mcrouter#111]
Hi, 

I'm planning to use mcrouter to better distribute the load we have on our memcache instances. I'm testing the Warmup route for the moment as it looks very useful when adding new instances. 
The one thing I cannot get my head around is: Why do the writes only go to the "cold" Pool? At some point in time you will have all the old keys into the cold pool, plus all the new keys. Meaning that you could basically swap the two pools, and start again. Is there any particular reason why the WarmUpRoute is set like this? ( The only reason I would do it like this, is if it's only meant to be used when decommissioning the servers in the "warm" pool ). 

EDIT: Sorry I forgot my current config ( Not sure it might be useful )
```json
{
  "pools": {
    "cold": { "servers": ["172.17.177.12:11212"]},
    "warm": { "servers": ["172.17.177.10:11212", "172.17.177.11:11212"]}
  },
   "route": {
     "type": "WarmUpRoute",
     "cold": "AllFastestRoute|Pool|cold",
     "warm": "AllFastestRoute|Pool|warm"
   }
}
```

Thanks!

**Comment by andreazevedo** [comment]
Hello @Shaps,

The `WarmUpRoute` was built this way to give us more control/flexibility. We can use it for a variety of scenarios, including decommissioning the warm pool as well as for a scenario like yours.
This route handle was created with the intention of being used temporarily, just while warming up the cold pool.

About your current config, there are somethings you can change in it to make it better. In general, you wouldn't want to use `RandomRoute` together with `WarmUpRoute`.

It would be good if you could tell us what exactly are you trying to achieve (e.g. After the warmup what's the expected state of the 3 memcached boxes? Are you decommissioning warm? Is `cold[0]` and `cold[1]` going to be replicas?)

Thank you,
Andre

**Comment by Shaps** [comment]
Hi @andreazevedo,
Thanks for your reply ;)

> About your current config, there are a few you can change in it to make it better. In general, you wouldn't want to use RandomRoute together with WarmUpRoute.
Why would you not use `RandomRoute`? 

I tested both `FailoverRoute` and `AllsyncRoute`, but I found `RandomRoute` to be a good compromise to get the cold cache warmed up quickly enough.

>It would be good if you could tell us what exactly you are trying to achieve (e.g. After the warmup, what's the expected state of the 3 memcached boxes? Are you decommissioning warm? Are cold[0] and cold[1] going to be replicas?).

Yes, in the end ( at least for now ) `cold[0]` and `cold[1]` will become replicas of `warm[0]`. I need them to be replicas mainly for resiliency. For now I have no way to implement routing for different datacenters/clusters/regions without being hit by some developers :)

So, the sort of end goal for now is to be able to create a mc instance, plug it into a `WarmUpRoute`, once warmed up move that to the warm pool. 
This brings me to one last question, how do you decide when a cold cache is ready to be moved to a warm pool? Just keep an eye to the % of hits for that instance? 


Thanks!

Andrea

**Comment by andreazevedo** [comment]
Hi @Shaps,

The problem with using RandomRoute with WarmUpRoute is that RandomRoute, as the name implies, is random :). WarmUpRoute in general assumes that the `cold` route is deterministic. Imagine the following scenario:
 - You send a get request for some key.
 - WarmUpRoute forwards the get to `cold`, which is a RandomRoute that then forwards the get to `cold[0]`.
 - `cold[0]` returns a miss.
 - WarmUpRoute sends the get to `warm`.
 - `warm` returns a a hit.
 - WarmUpRoute then sends an `add` to `cold`, but this time `RandomRoute` selects `cold[1]`.

You should also avoid `AllFastest` because it too is not deterministic (we cannot anticipate which server will return the response first).
So, in order to completely avoid that scenario, you should use `AllSync`.

About knowing when a cache box is warm, hit rate is usually a good indicator. :)

Now, if you want a more "automatic" way of slowly warming up and start sending requests to cold boxes, you can setup [slow_warmup](https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#poolroute) for PoolRoute. In that case, you can add new boxes to your pool and it will be slowly warmed up.

Andre

**Comment by Shaps** [comment]
Hi @andreazevedo,

Yes,that explanation does make a lot of sense :)
I will stick to `AllSync` for the `WarmUpRoute` then. 

I will find a way to test slow_warmup. For now, as I'm already monitoring the hits on the cache, I think I will just push a non warmup config to mcrouter once the nodes are warmed up. 

I think the `default_policy` with `FailoverRoute` is still a good idea.

**Comment by andreazevedo** [comment]
Hi @Shaps,

About the `default_policy`, the FailoverRoute is not necessary. Just remove `FailoverRoute` from both children and you will be good to go!
Let me know if you need help to set up something after you warm up the cold box!

Best regards,
Andre
