### ISSUE TITLE
Add/Remove nodes. Rebalancing

### ISSUE THREAD

**Issue by porunov** [facebook/mcrouter#112]
Hello,

I have several questions about a scaling up/down a memcached cluster with mcRouter.

1. Is it possible to add/remove nodes to the memcached cluster with mcRouter? If yes, then how?
2. Can we rebalance the cluster if several master nodes of the memcached cluster goes down?
3. Can we rebalance the cluster if we add new nodes?

Best Regards, Alexandr

**Comment by jagalan** [comment]
Hi Alexandr

1. I believe it is possible to do this by just changing the configuration file on-the-fly, the Mcrouter process will pick the changes up immediately and add/remove the nodes from the pools.

2-3. I think you misunderstood the purpose of Mcrouter because by no means it's a clustering solution. Hence concepts like 'master' and rebalancing do not exist, each node is equal and Mcrouter does not control which keys are where. For example when you remove a node from a pool you lose the keys in that node unless you had them replicated in another one (you can do so by using the All*Route routes for ADD/SET/DELETE operations). Likewise when you add a node it will be empty and only the traffic is going to fill it up again (not sure if the warmup routes can help with that, check the documentation)

Hope it helps

**Comment by porunov** [comment]
Jagalan,

Thank you for explanation.
How can we control keys?
I know that we can create keys controller with some algorithms like: hash({key})%{node count}
But I thought that mcRouter does it. 

Can you suggest me some links/books to read about a memcached cluster?

Sincerely, Alexandr

**Comment by andreazevedo** [comment]
Hello Alexandr,

> I really don't know what to do. I need some cache "magic" cluster in which I will able to add/remove/get data by key but in an other side, this "magic" cluster have to be scalable. Like add a node and this node will be automatically used and when I remove the node I will lose only data in the removed node but data in other nodes will be accessible.

This thing you described is pretty much what consistent hashing does. Mcrouter supports consistent hashing out-of-the box. In fact, it is the default options in `PoolRoute`.

With consistent hashing, you can add a server to a pool at the **end of the list** without reshuffling all keys around. Just a small portion of the keys will start pointing to the new server.
Similarly, you can shrink the pool by removing a server from the end of the list and you will lose just the keys going to that server.
You can also swap a server (remove a server from anywhere in the list and add another one at the exactly same place) without reshuffling all traffic.

Hope that helps,
Andre

**Comment by porunov** [comment]
Hello Andre,

Thank you for your help. 
It is exactly what I need

Sincerely, Alexandr

**Comment by andreazevedo** [comment]
No problem! Let us no if you need more information about it.
