### ISSUE TITLE
Just Need Some Clarification on Cold Caches

### ISSUE THREAD

**Issue by jamescarr** [facebook/mcrouter#114]
Great tool. I just need some help understanding the logic behind cache warming as described in https://github.com/facebook/mcrouter/wiki/Cold-cache-warm-up-setup. 

Say I have this scenario. I have a cluster of 2 caches and I want to upsize the cluster to 4 nodes. I can't just add 4 more caches to the route because that would skew consistent hashing and result in possibly lots of misses. 

So I'm surmising that I'll need to change the original cache route with 2 nodes to warm and add a cold cache route that has the 4 new instances I want to swap to. It seems then that gets would be attempted on the new cold pool and backfilled as needed until eventually all gets go against the new cache pool. At that point would I just go back to the original route with the 4 new nodes?

### Example

So say I have this configuration:

```json
 {
   "pools": {
     "main": { "servers": [ "cache1", "cache2"] }
   },
   "route": "PoolRoute|main"
 }

```

And I want to expand this to 4 so I change the configuration to the following:

```json
 {
   "pools": {
     "cold": { "servers": [ "cache3", "cache4", "cache5", "cache6"] },
     "main": { "servers": [ "cache1", "cache2" ] }
   },
   "route": {
     "type": "WarmUpRoute",
     "cold": "PoolRoute|cold",
     "warm": "PoolRoute|main"
   }
 }

```

So at this point, all gets should have zero misses on the client side and the cold route gets backfilled with sharding happening against the 4 new nodes, correct? Any misses on the cold route will get from the main route and backfill the cold route. 

So eventually on a long enough timeline we could inspect the 4 cache nodes and decide that it's good enough and change configuration to:

```json
 {
   "pools": {
     "main": { "servers":  [ "cache3", "cache4", "cache5", "cache6"]  }
   },
   "route": "PoolRoute|main"
 }
```

And everything keeps going without missing a beat, right?

**Comment by andreazevedo** [comment]
Hello James,
Yes, that sound correct! :)

**Comment by bryanhelmig** [comment]
So we experienced some surprising behavior using - you can't reliably delete data in a `WarmUpRoute`.

Since all deletes - usually invalidating data - goes to the `cold` pool - the old data in the `warm` pool gets moved to the `cold` on the next `get`. For example:

1. a key of `"hello"` has a value `"world"` in the `warm` pool
2. there is no `"hello"` in the `cold` pool
3. any gets of `"hello"` miss on the `cold` pool - is backfilled from `warm` :+1:
4. we invalidate/delete `"hello"` and it is removed from the `cold` pool but remains in `warm`
5. for any future gets of `"hello"` - see step 3 - surprisingly **the old value `"hello"` reappears**

I feel like invalidation via delete with lazy backfilling is a common enough practice to support deletes to both `cold` and `warm` (and sets too while we are at it /shrug) in a `WarmUpRoute`.

Is there a scenario that warrants sets/deletes to `cold` only that I am missing? Perhaps an alternative replicated setup could be documented nearby?

**Comment by andreazevedo** [comment]
Hello @bryanhelmig,

Yes, that is expected. With WarmUpRoute, the client (i.e. parent route) is responsible for replicating `set` and `delete`.
In order to achieve what you want, you need to put an OperationSelectorRoute in front of your WarmUpRoute and send deletes to both pools, possibly using a AllSyncRoute.
Issue #111 describes something similar, you might want to take a look at it too.

Best regards,
Andre

**Comment by jamescarr** [comment]
Thanks Andre!

**Comment by m8051** [comment]
@jamescarr I know it's been a while since you worked on this issue, giving a shot just in case you still remember what you did and how it went ...

We recently had an outage in our datacenter that caused issues to one of our mecached nodes and we would like to add/increase the capacity of our memcached nodes to make the system more resilient.

As far as I understood, the cold cache warmp up would do what we need, and I am wondering if you managed to replicate the 'set' and 'delete' to keep consistency across the memcached nodes in the different pools.

This is what I have been testing in my local environment:

```json
{
  "pools": {
    "cold": {
      "servers": [ "10.10.10.245:50002", "10.10.10.250:50003" ] },
    "warm": {
      "servers": [ "10.10.10.50:50001" ] }
  },
  "route": {
    "type": "OperationSelectorRoute",
      "operation_policies": {
        "get": {
          "type": "WarmUpRoute",
          "cold": "PoolRoute|cold",
          "warm": "PoolRoute|warm"
        },
        "set": "AllSyncRoute|Pool|cold",
        "add": "AllSyncRoute|Pool|cold",
        "delete": {
          "type": "AllSyncRoute",
          "children": ["Pool|cold", "Pool|warm"]
        }
      }
  }
}
```


I have a couple of question if you don't mind me asking:

- Did you come up with a better approach to deal with cold cache warm up?
- Were you able to run mcrouter on a Production environment successfully? I find this tool very useful, although I am struggling a bit to understand all the configuration opts and wonder how to run it as a service.

Thanks in advance.
