### ISSUE TITLE
Clarification on AllFastestRoute and delete operation

### ISSUE THREAD

**Issue by rsamin** [facebook/mcrouter#117]
Based on the documentation for AllFastestRoute, Mcrouter immediately sends the same request to all child route handles and returns the first non-error reply to come back.  However, I notice a slightly different behavior with the delete operation.  I configured AllFastestRoute delete with multiple children as follows:
```
----- snip -----
      },
      "delete": {
        "type": "AllFastestRoute",
        "children": [
          "PoolRoute|A",
          "PoolRoute|B",
          "PoolRoute|C"
        ]
      },
----- snip ----
```
The I brought down the servers in pool A and B, and issued an delete operation on a key that existed in pool C.  The operation seems to return NOT FOUND.  I would have expected DELETED to be returned as it would be the first non error response (from C, with rest of the servers down).  Not sure if this behavior is as expected.

Note: I tested AllFastestRoute on ADD operation, where some of its children had the key and some didn't.  The response was either STORED or NOT STORED, depending on whether the server with lower latency (from mcrouter) had the key or not.  This was as expected.

Any clarification would be appreciated.  Thanks.

**Comment by jmswen** [comment]
@rsamin, it sounds like you may want to run mcrouter with the `--asynclog-disable` option.  I am guessing that under your current setup, if you try to deliver a delete to a pool with all servers down, you will see `NOT_FOUND` instead of `SERVER_ERROR`.  By default, if mcrouter cannot deliver a delete (because the connection is down, etc.), the delete request will be logged to disk.  It is assumed that the user runs a separate process that reads from this "async log" file and retries the deletes periodically.  If you do not have a separate process that replays deletes, then you will want to run mcrouter with the `--asynclog-disable` option.  In this case, if mcrouter cannot deliver a delete, you will receive an error like `SERVER_ERROR unavailable` instead of `NOT_FOUND`, and this will give you the behavior you expect in `AllFastestRoute`.

**Comment by rsanr** [comment]
@jmswen thanks for the quick response!  `--asynclog-disable` seems to have done the trick.
