### ISSUE TITLE
Tag mcrouter release against Folly and Wangle release, instead of git revision 

### ISSUE THREAD

**Issue by samveen** [facebook/mcrouter#157]
As Folly and Wangle now follow a weekly release cycle, can mcrouter releases be pinned against the releases of the dependencies, instead of git commits in the dependencies?

**Comment by spalamarchuk** [comment]
Hi @samveen, unfortunately, we cannot do that easily. Internally we have all of these projects in one big repo and very often we have changes that touch all of them at the same time. So the only way we could pin against folly and wangle releases is if all three projects were cut at the same time. This won't work because we occasionally find issues during production testing (before the open source release is cut) and need to start from a new revision.
