### ISSUE TITLE
Help with this error (ProxyDestination.cpp:473)

### ISSUE THREAD

**Issue by vldadsniper** [facebook/mcrouter#166]
hello. help me pls what does it mean?

Dec 13 18:37:14 nod8 mcrouter-34-0[13063]: I1213 18:37:14.868008 13089 ProxyDestination.cpp:473] server memc.local:11411:ascii:plain:notcompressed-1000 closed (1 of 2)
Dec 13 18:37:14 nod8 mcrouter-34-0[13063]: I1213 18:37:14.868047 13089 ProxyDestination.cpp:473] server memc2.local:11311:ascii:plain:notcompressed-1000 closed (0 of 2)

**Comment by Steps09** [comment]
Hi @vldadsniper, this message barely means that mcrouter closed connections to two of your servers due to their inactivity in last 1-2 minutes. This is done to reduce amount of open sockets when you don't use them and there's nothing bad in this, as soon as you send a new request mcrouter will try to connect to the corresponding server.

There's also a command line argument "--reset-inactive-connection-interval" that controls this behavior. You can set it to 0 to disable this, but as I said there's nothing bad in them being closed.

**Comment by spalamarchuk** [comment]
@vldadsniper, does this answer you question? Can I close the issue?

**Comment by spalamarchuk** [comment]
Closing the issue, feel free to re-open if you require further help.
