### ISSUE TITLE
Not finding a way to ensure no stale data with replication

### ISSUE THREAD

**Issue by sergeyvladimirovich** [facebook/mcrouter#190]
I have 3 Memcached destinations to which I replicate all sets (using the AllMajorityRoute route handle for the set operation). 

Since documentation guarantees reliable delete stream, my client app precedes all sets with deletes. Delete operation is using the AllSyncRoute handle.

For the Get operation I tried various handles, such as  AllMajorityRoute and FailoverRoute. Here is my latest config:

_{
  "pools": {
        "A":{ 
               "servers":["10.216.30.44:11000",
                           "10.216.30.44:11001",
                           "10.216.30.44:11002"]
          }
       },
       "route": {
         "type": "OperationSelectorRoute",
         "operation_policies": {
            "add": "AllMajorityRoute|Pool|A",
            "delete": "AllSyncRoute|Pool|A",
            "get": "FailoverRoute|Pool|A",
            "set": "AllMajorityRoute|Pool|A",
            "incr": "AllMajorityRoute|Pool|A"
         }
       }
}_

When I introduce a comm failure on one of my 3 Memcached destinations, I inevitably end up with eventually receiving stale data from that destination (after I remove the comm failure from it, of course).

Is there a way to absolutely prevent stale data after a destination cycles in and out of commloss? If so, what kind of configuration do I need for that?

(Thinking about this abstractly, I am hoping that Mcrouter would issue a flush_all command to a destination that went into TOK and went out of TOK -- after all, that data has low value). 

Thanks!

**Comment by spalamarchuk** [comment]
Hi @sergeyvladimirovich, mcrouter provides "reliable delete stream" which is an asynchronous stream of failed deletes that should be retried. This stream needs to be consumed by other application or script and these deletes should be retried.

For more details read [reliable delete stream](https://github.com/facebook/mcrouter/wiki/Features#reliable-delete-stream) documentation.

We didn't opensource the tool for replaying these deletes because of certain internal dependencies, while the tool itself is relatively simple (~2k lines of code). But it should be easy to write a simple script that would tail asynchronous logs and retry deletes.

So to answer your question about how to prevent stale data, you need to start consuming failed deletes logs and retry them. This will guarantee eventual consistency.

As for the `flush_all`, you probably don't want to do that, since that will essentially clear your cache on any transient connectivity problem while your cache is still up to date, except it may miss several invalidations (think of network blip that caused unavailability for 1s).

**Comment by sergeyvladimirovich** [comment]
Appreciate the quick and clear reply, @spalamarchuk .
