### ISSUE TITLE
Accessing memached via mcrouter's routes

### ISSUE THREAD

**Issue by chilumbugeorge** [facebook/mcrouter#228]
Hello. We have some memcached servers that we use, and we plan to utilize mcrouter work as a router as well as provide HA solution for our memcached servers.

I have setup two nodes with mcrouter, and can connect to our memcache servers directly with a telnet command run on the mcrouter e.g., 

`telnet memcached_server_id 11211` 

But i have a strong feeling this is not the correct way of accessing memcached via mcrouter, and now want to find the best way to test accessing memcached via mcrouter. I have read about routes in mcrouter, and i am still a bit confused on how they work, the naming rules, and how they can be used to access memcached. 

So in my attempt to setup memcache (mcrouter + memcached), i did the following config in the mcrouter config file:

`
{
  "pools": {
    "memcache-notification": {
      "servers": [
        "10.1.9.100:11211",
        "10.1.9.101:11211"
      ]
    },
    "memcache-event": {
      "servers": [
        "10.1.9.200:11211",
        "10.1.1.201:11211"
      ]
    },
"memcache-shared": {
      "servers": [
        "[::1]:5000",
        "10.1.9.220:11211",
        "10.1.9.221:11211"
      ]
    }
  },
"route": {
     "type": "PrefixSelectorRoute",
     "policies": {
        "notification": "PoolRoute|memcache-notification",
        "event": "PoolRoute|memcache-event"
 },
     "wildcard": "PoolRoute|memcache-sharedl"
   }
}
`

Each pool contains memcached servers that have the same data, and should always be somewhat in sync and not sharded. So for example, all the hosts in the pool "notification" should have the same data, and so on and so forth. So i hope the config above allows that when you write to one memcached server in a pool, mcrouter will also write to the other memcached server in the same pool. So please advise if my above config is capable of doing that.

Lastly, given the config above, how can i test reading or writing to a memcached server via mcrouter using specified routes? For example, how can i use mcrouter to write or read to "notification" memcahed servers? What would be the command be for testing purposes in the terminal and not in the App?

**Comment by andreazevedo** [comment]
Hello @chilumbugeorge,

Given your config, to access `memcached` servers in the `memcache-notification` pool, you would have to prefix your keys with `notification`. Assuming your `mcrouter` is running on port 5000, you could do:
```bash
$ echo "get notification:my_key1" | nc localhost 5000
```
Quick tip about that: internally we use smaller key prefixes. So instead of `notification`, we would use something like `not`. That way you use less network, less memory in memcached servers, and less cpu (to hash keys).

About the replication, you can take a look at our [replicated pools setup wiki page](https://github.com/facebook/mcrouter/wiki/Replicated-pools-setup).

Feel free to reopen the issue if you have more questions.

Thank you,
Andre
