### ISSUE TITLE
Data load after memcached server reboot

### ISSUE THREAD

**Issue by chilumbugeorge** [facebook/mcrouter#236]
I have setup a pool in mcrouter for two memcached servers with the replication route config in hope to have the same data in both memcached servers belonging to the same pool.

I was wondering what happens when one of the memcached serves is rebooted, does mcrouter have a way to load data from the currently alive memached server into the crashed server once its back up from a reboot? How does memcached handle this to make sure the rebooted memcached gets in sync with the other server?

A sample code to handle this would be much appreciated if possible.

**Comment by spalamarchuk** [comment]
On a restart, Memcached would lose all the data it had. It doesn't have any mechanism to recover it from somewhere else.

Mcrouter provides several instruments that help with recovery from one box going down.

**[MissFailoverRoute](https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#missfailoverroute)** - this route handle on a miss would go to another box and return result from it. It DOES NOT store that value back into the original box.
**[WarmUpRoute](https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#warmuproute)** - this route handle would similarly to MissFailoverRoute on a miss go to another instance but on a hit it would store the value back to the box that returned a miss.

The drawback of these is that on misses you always go to another box.

An additional drawback of WarmUpRoute is that you may increase the number of inconsistencies. An example of such inconsistency would be that due to race you may "resurrect" a value that was just deleted (but the other box didn't receive the delete yet).

Note, it's important to remember that Memcached is a cache after all.
