### ISSUE TITLE
RPM for CentOS

### ISSUE THREAD

**Issue by daniel-lucio** [facebook/mcrouter#269]
https://inside-out.xyz/technology/memcached-protocol-router-rpm-for-centos-7.html

RPM for everybody, enjoy if you need it.

I did try to build for CentOS6, but I have some python problems when building Boost 1.66 under CentOS6. If someone has an SRPM of Bostt166+ that builds correctly under Centos 6 I will gladly publish the package.

**Comment by alex-phillips** [comment]
@daniel-lucio just curious - how did you manage to build this for centos since most of the available libraries are out of date?

**Comment by jsettypalli** [comment]
Hi,
I installed mcrouter using the rpm.  mcrouter service doesn't start. The script comes back with status code 127. I know /usr/bin/mcrouter exists and has execute permission.  I am guessing it is something to do with one of the dependent packages.

I followed below steps for installation.

- sudo yum install epel-release
- sudo rpm -ivh http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-3.el7.noarch.rpm?
- sudo yum install mcrouter

I disabled gpgcheck in okay.repo (set the value to zero) as the installation was failing with below error otherwise.
`Public key for boost166-chrono-1.66.0-16.el7.x86_64.rpm is not installed`

Appreciate if you can give some pointers to fix the issue.

Thanks

**Comment by jsettypalli** [comment]
Never mind. This is fixed.  I installed below dependencies and mcrouter starts fine.

- sudo yum install -y centos-release-scl
- sudo yum install -y  autoconf  binutils-devel  bison  boost-devel  cmake  double-conversion-devel  flex  git  gflags-devel  glog-devel  gtest-devel  jemalloc-devel  libtool  libevent-devel  make  openssl-devel python-devel  ragel

**Comment by daniel-lucio** [comment]
what Centos are you using 7 or 8? I don't recall that the RPM asks for -devel packages.

**Comment by jsettypalli** [comment]
Apologies for the late response. I am using CentOS 7.

________________________________

**Comment by t0mtaylor** [comment]
https://github.com/facebook/mcrouter/issues/393
