### ISSUE TITLE
flush_all doesn't work

### ISSUE THREAD

**Issue by 0xd3adsh3ll** [facebook/mcrouter#29]
Hello, I have mcrouter 1.0
When I try flushed all data I get this error:
telnet mcrouter.local 5001
Trying 172.18.45.240...
Connected to mcrouter.local.
Escape character is '^]'.
flush_all
SERVER_ERROR Command not supported
My config http://pastebin.com/npJagT9x
Can you help me please?
Thanks.

**Comment by 0xd3adsh3ll** [comment]
I tried to clear the cache with command:
echo -ne "flush_all\r\n" | nc 0 5000
SERVER_ERROR Command not supported
But get an error.

Also, my php app can't reset cache via memcache: http://php.net/manual/en/memcache.flush.php

php_app (do action reset_cache)
|
| -- php_method (Memcache::flush ( mcrouter.local:5001 ))
|
| -- part of syslog error: [2015-02-16 13:40:18] project.ERROR: could not connect to memcache {"host":"mcrouter.local","port":5001.....

**Comment by pavlo-fb** [comment]
@0xd3adsh3ll thanks for the report. We explicitly disabled **flush_all** and **flush_regex** commands, because it may be very destructive to replicate them via mcrouter (it is very easy to break everything if some broken script sends those commands to production boxes). See https://github.com/facebook/mcrouter/blob/master/mcrouter/McrouterClient.cpp#L33

What is your use case? If it is only for debugging/testing, we can add the support, but guard it with some command line option (like --enable-flush-command or --debug-mode).

**Comment by 0xd3adsh3ll** [comment]
Hello, @pavlo-fb,
Memcache::flush needs for new releases of our projects:

ansible
|
|-- production_servers (remove old code, create new release folder, prepare env)
|-- control_panel (clear all cached data after release because we stored some temporary settings in cache which must be removed.)

I have question, if send flush_all directly on memcached servers bypassing mcrouter? It's possible?
Thanks.

|--

**Comment by ryanmce** [comment]
Yes, mcrouter doens't modify the behavior of memcached at all, so if you
send a flush all command directly to the memcached server, it will behave
normally.

**Comment by 0xd3adsh3ll** [comment]
@ryanmce, thanks!
If @pavlo-fb can enable: "If it is only for debugging/testing, we can add the support, but guard it with some command line option (like --enable-flush-command or --debug-mode)" It's be a perfectly.

**Comment by 0xd3adsh3ll** [comment]
Hello, @pavlo-fb, @ryanmce tell me please, you can enable "--enable-flush-command"?
Thanks.

**Comment by andreazevedo** [comment]
Hello @0xd3adsh3ll,
As @pavlo-fb said, these commands are very dangerous to be replicated via mcrouter. You should consider bypassing mcrouter for these specific statements and sending it straight to the memcached box you intend too.
That being said, if you really think you need/want to use these commands with mcrouter, let me know and I will re-prioritize and get this done for you sooner rather than later.
Thanks.

**Comment by 0xd3adsh3ll** [comment]
Hello @andreazevedo, 
Thanks for your reply, I understand the risk but could you please enable "flush_all"  via mcrouter, this need for our project.
Thanks.

**Comment by andreazevedo** [comment]
Hello @0xd3adsh3ll,
We just pushed a new version of mcrouter that adds support to `flush_all` (commit 3cb8ca22adf8e7a8bdeac8d390d4e98a07f834ed). You just need to specify the `--enable-flush-cmd` command-line option.

**Comment by 0xd3adsh3ll** [comment]
Hello @andreazevedo,
Thanks a lot :)
