### ISSUE TITLE
Failed to build on Ubuntu 24.04

### ISSUE THREAD

**Issue by phoenixlam** [facebook/mcrouter#447]
Anyone can provide the build script for Ubuntu 24.04?

**Comment by mszabo-wikia** [comment]
Hello,

The easiest would probably be to base your buildenv on https://gerrit.wikimedia.org/r/plugins/gitiles/operations/debs/mcrouter/+/refs/heads/master. Once you swap out for an Ubuntu base image, you'll likely need to change some APT dependencies (e.g. the boost version) and pin the other FB library dependencies to a more recent commit. The latest `vYYYY.MM.DD` tags usually work well together, but there are often cases where the OSS build for one of the deps is broken on a given tag, in which case you'll need to pin that particular dep to a newer or older, working, tag.

Once you do that, you'll also need to apply https://github.com/facebook/mcrouter/pull/445 as part of your build process since the autotools build is out of sync with recent changes.

**Comment by guieusebiogaspar** [comment]
Did the devs stopped working on these scripts?

**Comment by mszabo-wikia** [comment]
I would assume so. I have made a PR to replace the autotools build system with CMake, which should then allow building mcrouter using the `getdeps.py` script used by other Meta OSS C++ projects, such as fbthrift. That script automates the process of obtaining or compiling dependencies, so it should be much simpler to use, and it should obviate the need for such per distro/per release scripts.
