### ISSUE TITLE
Is it necessary to require autoreconf during build?

### ISSUE THREAD

**Issue by eherot** [facebook/mcrouter#69]
Is there a reason you guys chose not to run `autoreconf --install` against the source tree *before* zipping it up? Deviating from the standard `./configure && make && make install` procedure is kind of an anti-pattern and prevents me from being able to use a handy built-in build action in the `ark` cookbook (for Chef).

See: http://stackoverflow.com/questions/19263899/why-is-autoreconf-not-used-often

Same goes for the `folly` project...

**Comment by alikhtarov** [comment]
Hi, the reason is that we simply wouldn't want to commit auto-generated files to the source repo, but I'd like to see the answer from folly maintainers as well - do you mind filing a similar issue there?

**Comment by fugalh** [comment]
The "already autoconf'd" workflow works great for distributions of tarballs and other conglomerations of released files. It kind of breaks down with a version-control scheme like github. It would be an unportable antipattern to check in autotools-generated artifacts into version control, and since you just clone github or maybe an automatic tarball from github, you have to do the autoreconf step yourself.

**Comment by eherot** [comment]
That makes sense (and does seem to be supported by the community) so I have an alternative suggestion: Would you be willing to put the `autoreconf --install` command into an `autogen.sh` script? That does seem to be a [standard practice](http://stackoverflow.com/questions/3290908/which-files-generated-by-autotools-should-i-keep-in-version-control-repository) and it is also consequently [natively supported by ark](https://github.com/burtlo/ark/blob/master/providers/default.rb#L292).

**Comment by eherot** [comment]
Submitted #70 just in case ;-)

**Comment by alikhtarov** [comment]
Yeah that seems reasonable
