### ISSUE TITLE
mcroute sends keys to hard TKO memcache as before

### ISSUE THREAD

**Issue by meishd** [facebook/mcrouter#86]
my configure file:
{
  "pools": {
    "A": {
      "servers": [
        "192.168.188.150:11217",
        "192.168.188.150:11218"
      ]
    }
  },
  "route": "PoolRoute|A"
}

k1 to k8 should send to memcache with port 11218 because of default hash function.

13:37:12 set k1 true
13:37:17 set k2 true
13:37:22 set k3 true

13:37:24  
ps -ef | grep memcached | grep 11218 | grep -v grep | awk '{print $2}' | xargs kill -9

I0901 13:37:24.532399 28313 ProxyDestination.cpp:304] 192.168.188.150:11218 (A) marked hard TKO. Total hard TKOs: 1; soft TKOs: 0. Reply: mc_res_connect_error

13:37:27 set k4 false
13:37:32 set k5 false
13:37:37 set k6 false

11218 has been marked hard TKO, why subsequenct requests is sented to it also.

what does next statement mean from the wike?
Normal requests would be failed over to a backup destination immediately (without waiting for further timeouts).

**Comment by pavlo-fb** [comment]
On TKO mcrouter doesn't send the request over the wire (feel free to check it with [ngrep](http://ngrep.sourceforge.net/) or similar tools), but since it has no other destination to send to, it will return an error. To provide another destination in case of an error, use [Failover route](https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#failoverroute) or another route which provide "retry on error" logic (e.g. FailoverWithExptimeRoute, LatestRoute, etc.).

For example, to send all add/delete/set requests to both servers and send all gets to one of them and failover to another you may use approach described in [Replicated pools](https://github.com/facebook/mcrouter/wiki/Replicated-pools-setup).

For your case the config may look like this:
```
{
   "pools": {
      "A": {
         "servers": [
           "192.168.188.150:11217",
           "192.168.188.150:11218"
         ]
      }
   },
   "route": {
     "type": "OperationSelectorRoute",
     "operation_policies": {
       "add": "AllSyncRoute|Pool|A",
       "delete": "AllSyncRoute|Pool|A",
       "get": "FailoverRoute|Pool|A",
       "set": "AllSyncRoute|Pool|A"
     }
   }
 }
```

**Comment by andreazevedo** [comment]
Hello @meishd,

I'm closing this issue, but few free to re-open it if you have further questions.

Thank you!
