### ISSUE TITLE
Can someone explain SlowWarmUpRoute to me?

### ISSUE THREAD

**Issue by kevinquinnyo** [facebook/mcrouter#99]
It seems to exist as a route, and *sounds* like it might be able to help me warm up cold memcached nodes when they come into existence, but I'm not sure how it works and there doesn't seem to be a corresponding update in the Wiki.

Right now, I'm replicating all sets, updates, deletes to all memcached nodes, and I use WarmUpRoute for get, gets.

Each of my webservers runs it's own mcrouter instance and when a new memcached node comes online, it's ip is appended to the "shared" pool.

This means that if the cold memcached node happens to be queried, it will consult with another node, get the value and store it.  This is fine, since after enough time, it will be more or less warmed up.

If the SlowWarmUpRoute does the warming somehow on it's own, I'd like to know.  I think it would be nice if a new node could be auto-warmed by the others somehow.

Hope that makes sense.  Thanks for the help.

**Comment by kevinquinnyo** [comment]
Hmm.  Geussing here.  Dows SlowWarmUpRoute not send gets to cold instances until it has been "warmed up" enough with enough sets?

**Comment by andreazevedo** [comment]
Hello @kevinquinnyo,

Your setup looks fine. You can give a try to SlowWarmUpRoute if you want. Here is how it works:

 - SlowWarmUpRoute will keep track of the hit ratio of each one your memcached instances.
 - Once the hit ratio drops bellow a certain threshold (70% by default) it "enables" the slow warmup process. So, if for example you add a new cold memcached instance to your pool, the hit ratio will be 0%, which means it will start the slow warmup process right away.
 - When the slow warmup process is enabled, all that happens is that a percentage of your requests are routed directly to the `failoverTarget` instead of first "wasting" a roundtrip to the cold memcached box. The percentage of the requests that are sent to the cold box is, by default, 10% + the hit ratio (so if your hit ratio is currently 15%, 25% of the requests will go to the cold box).
 - Once the hit ratio goes above a certain threshold (90% by default), the slow warmup route is disabled.
 - One thing to keep in mind is that the SlowWarmUpRoute only affects get-like operations. You still want to replicate all your sets/deletes to actually warmup the host. All that the SlowWarmUpRoute does is keeping track of the hit ratio to avoid some "useless" round trips to keep the latency low when you have cold boxes. 

Here are the 2 places where you can find more information on how SlowWarmUpRoute works:
1) https://github.com/facebook/mcrouter/wiki/List-of-Route-Handles#poolroute, at `slow_warmup` section.
2) https://github.com/facebook/mcrouter/blob/master/mcrouter/routes/SlowWarmUpRoute.h#L30-L62

Let me know if that helped!

**Comment by kevinquinnyo** [comment]
@andreazevedo Awesome explanation.  Thanks!
